
if(NOT LIBLMS7COMPACT_FOUND)
	if(NOT WIN32)
		include(FindPkgConfig)
		pkg_check_modules (LIBLMS7COMPACT_PKG LIBLMS7COMPACT)
	endif(NOT WIN32)

	find_path(LIBLMS7COMPACT_INCLUDE_DIRS NAMES liblms7002m.h
		PATHS
		${LIBLMS7COMPACT_PKG_INCLUDE_DIRS}
		/usr/include/
		/usr/local/include/
		)

	find_library(LIBLMS7COMPACT_LIBRARIES NAMES lms7compact
		PATHS
		${LIBLMS7COMPACT_PKG_LIBRARY_DIRS}
		/usr/lib
		/usr/local/lib
		)

	if(LIBLMS7COMPACT_INCLUDE_DIRS AND LIBLMS7COMPACT_LIBRARIES)
		set(LIBLMS7COMPACT_FOUND TRUE CACHE INTERNAL "LIBLMS7COMPACT found")
		message(STATUS "Found liblms7mcompact: ${LIBLMS7COMPACT_INCLUDE_DIRS}, ${LIBLMS7COMPACT_LIBRARIES}")
	else(LIBLMS7COMPACT_INCLUDE_DIRS AND LIBLMS7COMPACT_LIBRARIES)
		set(LIBLMS7COMPACT_FOUND FALSE CACHE INTERNAL "LIBLMS7COMPACT found")
		message(STATUS "liblms7compact not found.")
	endif(LIBLMS7COMPACT_INCLUDE_DIRS AND LIBLMS7COMPACT_LIBRARIES)

	mark_as_advanced(LIBLMS7COMPACT_LIBRARIES LIBLMS7COMPACT_INCLUDE_DIRS)

endif(NOT LIBLMS7COMPACT_FOUND)
